name: gimagereader
version: 3.4.2
summary: A Gtk/Qt front-end to tesseract-ocr.
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

base: core24
confinement: devmode # use 'strict' once you have the right plugs and slots
adopt-info: gimagereader
compression: lzo

layout:
  /usr/share/tesseract-ocr:
    bind: $SNAP/usr/share/tesseract-ocr

apps:
  gimagereader:
    extensions: [gnome]
    command: usr/bin/gimagereader-gtk
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      # Included temporarily until https://github.com/snapcore/snapcraft-desktop-integration/issues/28
      # is resolved.
      NOTIFY_IGNORE_PORTAL: 1
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - gsettings
      - browser-support
      - home
      - network
      - removable-media
      - unity7

parts:
  gimagereader:
    plugin: cmake
    source: https://github.com/manisandro/gImageReader.git
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DINTERFACE_TYPE=gtk
      - -DENABLE_VERSIONCHECK=0
    build-packages:
      - debhelper-compat
      - intltool
      - libcairomm-1.0-dev
      - libdjvulibre-dev
      - libenchant-2-dev
      - libgtkmm-3.0-dev
      - libgtksourceviewmm-3.0-dev
      - libgtkspellmm-3.0-dev
      - libjpeg-dev
      - libjson-glib-dev
      - libpangomm-1.4-dev
      - libpodofo-dev
      - libpoppler-glib-dev
      - libpoppler-qt5-dev
      - libqtspell-qt5-dev
      - libquazip5-dev
      - libsane-dev
      - libtesseract-dev
      - libxml++2.6-dev
      - libzip-dev
      - python3-gi
      - qtbase5-dev
      - uuid-dev
    stage-packages:
      - libtesseract5
      - tesseract-ocr-all
      - tesseract-ocr
      - dconf-gsettings-backend
      - gsettings-backend
      - libatkmm-1.6-1v5
      - libc6
      - libcairomm-1.0-1v5
      - libdjvulibre21
      - libenchant-2-2
      - libfontconfig1
      - libgcc-s1
      - libglib2.0-0t64
      - libglibmm-2.4-1t64
      - libgomp1
      - libgtk-3-0t64
      - libgtkmm-3.0-1t64
      - libgtksourceviewmm-3.0-0v5
      - libgtkspellmm-3.0-0v5
      - libjpeg8
      - libjson-glib-1.0-0
      - libpangocairo-1.0-0
      - libpangomm-1.4-1v5
      - libpodofo0.9.8t64
      - libpoppler-glib8t64
      - libsane1
      - libsigc++-2.0-0v5
      - libstdc++6
      - libxml++2.6-2v5
      - libzip4t64

  spellchecker:
    after: [gimagereader]
    plugin: nil
    stage-packages:
      - hunspell
      - hunspell-af
      - hunspell-an
      - hunspell-ar
      - hunspell-be
      - hunspell-bg
      - hunspell-bn
      - hunspell-bo
      - hunspell-br
      - hunspell-bs
      - hunspell-ca
      - hunspell-cs
      - hunspell-da
      - hunspell-de-at
      - hunspell-de-at-frami
      - hunspell-de-ch
      - hunspell-de-ch-frami
      - hunspell-de-de
      - hunspell-de-de-frami
      - hunspell-de-med
      - hunspell-dz
      - hunspell-el
      - hunspell-en-au
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-med
      - hunspell-en-us
      - hunspell-en-za
      - hunspell-eo
      - hunspell-es
      - hunspell-eu
      - hunspell-fr
      - hunspell-fr-classical
      - hunspell-fr-comprehensive
      - hunspell-fr-revised
      - hunspell-gd
      - hunspell-gl
      - hunspell-gu
      - hunspell-gug
      - hunspell-he
      - hunspell-hi
      - hunspell-hr
      - hunspell-hu
      - hunspell-id
      - hunspell-is
      - hunspell-it
      - hunspell-kk
      - hunspell-kmr
      - hunspell-ko
      - hunspell-lo
      - hunspell-lt
      - hunspell-lv
      - hunspell-ml
      - hunspell-mn
      - hunspell-ne
      - hunspell-nl
      - hunspell-no
      - hunspell-oc
      - hunspell-pl
      - hunspell-pt-br
      - hunspell-pt-pt
      - hunspell-ro
      - hunspell-ru
      - hunspell-si
      - hunspell-sk
      - hunspell-sl
      - hunspell-sr
      - hunspell-sv
      - hunspell-sw
      - hunspell-te
      - hunspell-th
      - hunspell-tr
      - hunspell-uk
      - hunspell-uz
      - hunspell-vi
      - myspell-bg
      - myspell-cs
      - myspell-da
      - myspell-de-de-1901
      - myspell-el-gr
      - myspell-en-au
      - myspell-eo
      - myspell-es
      - myspell-et
      - myspell-fa
      - myspell-fo
      - myspell-fr
      - myspell-fr-gut
      - myspell-ga
      - myspell-gd
      - myspell-gv
      - myspell-he
      - myspell-hu
      - myspell-hy
      - myspell-nb
      - myspell-nn
      - myspell-nr
      - myspell-ns
      - myspell-pt
      - myspell-sk
      - myspell-sq
      - myspell-ss
      - myspell-st
      - myspell-tl
      - myspell-tn
      - myspell-ts
      - myspell-uk
      - myspell-ve
      - myspell-xh
      - myspell-zu
      
package-repositories:
  - type: apt
    ppa: alex-p/tesseract-ocr-devel
    priority: always
